// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package forms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/user/janitarr/src/database"
import "fmt"

func ConfigForm(config database.AppConfig, logCount int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form hx-post=\"/api/config\" hx-swap=\"none\" x-data=\"{\n\t\t\tloading: false,\n\t\t\tsuccess: false,\n\t\t\twarning: '',\n\t\t\tmissingMovies: parseInt(document.getElementById('missing-movies')?.value || '0'),\n\t\t\tmissingEpisodes: parseInt(document.getElementById('missing-episodes')?.value || '0'),\n\t\t\tcutoffMovies: parseInt(document.getElementById('cutoff-movies')?.value || '0'),\n\t\t\tcutoffEpisodes: parseInt(document.getElementById('cutoff-episodes')?.value || '0'),\n\t\t\thasHighLimit() {\n\t\t\t\treturn this.missingMovies > 100 || this.missingEpisodes > 100 || this.cutoffMovies > 100 || this.cutoffEpisodes > 100;\n\t\t\t}\n\t\t}\" @htmx:before-request=\"loading = true\" @htmx:after-request=\"loading = false; success = true; warning = $event.detail.xhr.response ? JSON.parse($event.detail.xhr.response).data?.warning || '' : ''; setTimeout(() => { success = false; warning = ''; }, 5000)\" class=\"space-y-6\"><!-- Schedule Settings --><div class=\"card bg-base-100 shadow-xl\"><div class=\"card-body\"><h2 class=\"card-title\">Schedule</h2><div class=\"space-y-4\"><div class=\"form-control w-full\"><label class=\"label\"><span class=\"label-text\">Interval (hours)</span></label> <input type=\"number\" id=\"interval\" name=\"schedule.interval\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.Schedule.IntervalHours))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/components/forms/config_form.templ`, Line: 38, Col: 63}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" min=\"1\" max=\"168\" required class=\"input input-bordered w-full\"> <label class=\"label\"><span class=\"label-text-alt\">How often to run the automation cycle (1-168 hours)</span></label></div><div class=\"form-control\"><label class=\"label cursor-pointer justify-start gap-4\"><input type=\"checkbox\" id=\"enabled\" name=\"schedule.enabled\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.Schedule.Enabled {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " checked")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " value=\"true\" class=\"checkbox checkbox-primary\"> <span class=\"label-text\">Enable scheduler</span></label></div></div></div></div><!-- Search Limits --><div class=\"card bg-base-100 shadow-xl\"><div class=\"card-body\"><h2 class=\"card-title\">Search Limits</h2><div class=\"space-y-4\"><div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><div class=\"form-control w-full\"><label class=\"label\"><span class=\"label-text\">Missing Movies</span></label> <input type=\"number\" id=\"missing-movies\" name=\"limits.missing.movies\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.SearchLimits.MissingMoviesLimit))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/components/forms/config_form.templ`, Line: 76, Col: 73}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" min=\"0\" max=\"1000\" required class=\"input input-bordered w-full\" x-model.number=\"missingMovies\"></div><div class=\"form-control w-full\"><label class=\"label\"><span class=\"label-text\">Missing Episodes</span></label> <input type=\"number\" id=\"missing-episodes\" name=\"limits.missing.episodes\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.SearchLimits.MissingEpisodesLimit))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/components/forms/config_form.templ`, Line: 91, Col: 75}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" min=\"0\" max=\"1000\" required class=\"input input-bordered w-full\" x-model.number=\"missingEpisodes\"></div></div><div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><div class=\"form-control w-full\"><label class=\"label\"><span class=\"label-text\">Cutoff Movies</span></label> <input type=\"number\" id=\"cutoff-movies\" name=\"limits.cutoff.movies\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.SearchLimits.CutoffMoviesLimit))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/components/forms/config_form.templ`, Line: 108, Col: 72}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" min=\"0\" max=\"1000\" required class=\"input input-bordered w-full\" x-model.number=\"cutoffMovies\"></div><div class=\"form-control w-full\"><label class=\"label\"><span class=\"label-text\">Cutoff Episodes</span></label> <input type=\"number\" id=\"cutoff-episodes\" name=\"limits.cutoff.episodes\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.SearchLimits.CutoffEpisodesLimit))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/components/forms/config_form.templ`, Line: 123, Col: 74}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" min=\"0\" max=\"1000\" required class=\"input input-bordered w-full\" x-model.number=\"cutoffEpisodes\"></div></div><div x-show=\"hasHighLimit()\" x-transition class=\"alert alert-warning\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"stroke-current shrink-0 h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z\"></path></svg> <span class=\"text-sm\">High limits may impact performance and trigger rate limiting on your media servers.</span></div><p class=\"text-sm text-base-content/70\">Maximum number of searches to trigger per category per cycle</p></div></div></div><!-- Logs Settings --><div class=\"card bg-base-100 shadow-xl\"><div class=\"card-body\"><h2 class=\"card-title\">Log Retention</h2><div class=\"space-y-4\"><div class=\"form-control w-full\"><label class=\"label\"><span class=\"label-text\">Retention Period (days)</span></label> <select id=\"retention-days\" name=\"logs.retention_days\" class=\"select select-bordered w-full\"><option value=\"7\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.Logs.RetentionDays == 7 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, ">7 days</option> <option value=\"14\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.Logs.RetentionDays == 14 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, ">14 days</option> <option value=\"30\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.Logs.RetentionDays == 30 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, ">30 days (default)</option> <option value=\"60\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.Logs.RetentionDays == 60 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, ">60 days</option> <option value=\"90\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.Logs.RetentionDays == 90 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, ">90 days</option></select> <label class=\"label\"><span class=\"label-text-alt\">Logs older than this period will be automatically deleted</span></label></div><div class=\"text-sm text-base-content/70\">Current log count: <span class=\"font-medium\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", logCount))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/components/forms/config_form.templ`, Line: 167, Col: 80}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</span> entries</div></div></div></div><!-- Save Button --><div class=\"space-y-3\"><div class=\"flex items-center gap-3\"><button type=\"submit\" x-bind:disabled=\"loading\" class=\"btn btn-primary\"><span x-show=\"!loading\">Save Settings</span> <span x-show=\"loading\" class=\"flex items-center gap-2\"><span class=\"loading loading-spinner loading-sm\"></span> Saving...</span></button><div x-show=\"success\" x-transition class=\"text-sm text-success\">Settings saved successfully!</div></div><div x-show=\"warning\" x-transition class=\"alert alert-warning\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"stroke-current shrink-0 h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z\"></path></svg> <span class=\"text-sm\" x-text=\"warning\"></span></div></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
